name: Despliegue Automático SER (CI/CD)

on:
  push:
    branches: [ "main" ]

jobs:
  construir-y-desplegar:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código fuente
      uses: actions/checkout@v3

    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir y subir imagen a Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/api-emociones:latest


    - name: Conectar a AWS y actualizar el contenedor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/api-emociones:latest
          
          sudo docker stop api_emo || true
          sudo docker rm api_emo || true

          # Se mapea el puerto 5000 y se conecta a la carpeta del modelo de AWS al contenedor
          sudo docker run -d \
            -p 5000:5000 \
            -v /home/ubuntu/clasificacion-emociones-audio/tablero/model:/app/tablero/model \
            --name api_emo \
            ${{ secrets.DOCKER_USERNAME }}/api-emociones:latest
          
          sudo docker image prune -f
